name: deploy gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          yarn install
          CI=false && yarn run build
        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          branch: gh-pages
          folder: build